;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Message.Health_Potion",NewTagName="Message.HealthPotion")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attributes.Vital.Health",DevComment="玩家的生命值")
+GameplayTagList=(Tag="Attributes.Vital.Mana",DevComment="法力值")
+GameplayTagList=(Tag="Event.Montage.Attack.Melee",DevComment="近战普通攻击标签")
+GameplayTagList=(Tag="Event.Montage.Electrocute",DevComment="")
+GameplayTagList=(Tag="Event.Montage.FireBolt",DevComment="释放火球动画事件")
+GameplayTagList=(Tag="GameplayCue.MeleeImpact",DevComment="近战攻击命中效果")
+GameplayTagList=(Tag="GameplayCue.ShockBurst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShockLoop",DevComment="")
+GameplayTagList=(Tag="Message.HealthCrystal",DevComment="")
+GameplayTagList=(Tag="Message.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Message.ManaCrystal",DevComment="")
+GameplayTagList=(Tag="Message.ManaPotion",DevComment="")

